#!/usr/bin/env python3
"""
AtlasPS2 - generate LZ4 test vectors from the reference compressor.

    python3 tools/genlz4vec.py > tests/lz4_vectors.h

The output is committed, so `make check` needs neither Python nor the
lz4 module. Regenerate only when adding a case.

WHY THE VECTORS COME FROM SOMEWHERE ELSE
----------------------------------------
A decoder checked against its own encoder can be uniformly wrong and
never notice: both sides agree, and the file still fails to open on
every other tool. These blocks are produced by the reference LZ4
compressor, so decoding them to the exact original bytes is evidence
about interoperability rather than about self-consistency.

The cases are chosen for the situations a real ZSO puts a decoder in,
not for coverage of the format: long zero runs (the padding between a
disc's files), an incompressible block (encrypted or already-compressed
game data, which LZ4 stores as literals and which is the worst case for
throughput), and a block that fills a whole 2 KB sector.
"""
import lz4.block

CASES = [
    # (name, bytes, why this case exists)
    ("hello", b"Hello",
     "the smallest complete block: literals only, no match"),

    ("run", b"a" * 22,
     "an overlapping match at offset 1 - a run, where memcpy() and\n"
     " * memmove() both give a different answer than the format defines"),

    ("pattern", b"abc" * 4,
     "a match whose length exceeds its offset, so the copy reads bytes\n"
     " * it is itself writing"),

    ("literals", bytes((ord('A') + i) % 256 for i in range(300)),
     "a literal run long enough to need a length continuation byte"),

    ("zeros", b"\x00" * 2048,
     "a full sector of padding, which is most of a disc's slack space"),

    ("incompressible", bytes((i * 37 + 11) % 256 for i in range(2048)),
     "a full sector that does not compress: encrypted or already\n"
     " * compressed game data, stored as literals, and the throughput\n"
     " * worst case"),

    ("sector", (b"\x00" * 300) + b"SYSTEM.CNF;1" + (b"\x00" * 700)
               + (b"\xAB\xCD" * 518),
     "a mixed sector: padding, a filename, then repeating data - the\n"
     " * shape of a real ISO9660 directory sector"),
]


def emit_array(name, data):
    print("static const unsigned char %s[] = {" % name)
    for i in range(0, len(data), 16):
        row = ", ".join("0x%02X" % b for b in data[i:i + 16])
        print("    %s%s" % (row, "," if i + 16 < len(data) else ""))
    print("};")


def main():
    print("/*")
    print(" * AtlasPS2 - lz4_vectors.h")
    print(" *")
    print(" * GENERATED by tools/genlz4vec.py from the reference LZ4")
    print(" * compressor. Do not edit; regenerate.")
    print(" *")
    print(" * Each case is a compressed block and the exact bytes it must")
    print(" * decode to. They come from the reference implementation rather")
    print(" * than from this project's own code, because a decoder checked")
    print(" * against its own encoder can be uniformly wrong and still")
    print(" * agree with itself.")
    print(" */")
    print("#ifndef ATLAS_LZ4_VECTORS_H")
    print("#define ATLAS_LZ4_VECTORS_H")
    print()

    for name, raw, why in CASES:
        comp = lz4.block.compress(raw, store_size=False,
                                  mode="high_compression")

        # Refuse to emit a vector the reference cannot itself round-trip.
        assert lz4.block.decompress(comp, uncompressed_size=len(raw)) == raw

        print("/*")
        print(" * %s: %d bytes compressed to %d." % (name, len(raw), len(comp)))
        print(" *")
        print(" * %s." % why)
        print(" */")
        emit_array("v_%s_c" % name, comp)
        emit_array("v_%s_r" % name, raw)
        print()

    print("static const struct {")
    print("    const char          *name;")
    print("    const unsigned char *comp;")
    print("    int                  comp_len;")
    print("    const unsigned char *raw;")
    print("    int                  raw_len;")
    print("} k_lz4_vectors[] = {")
    for name, _, _ in CASES:
        print('    { "%s", v_%s_c, (int)sizeof(v_%s_c),'
              % (name, name, name))
        print('      v_%s_r, (int)sizeof(v_%s_r) },' % (name, name))
    print("};")
    print()
    print("#endif /* ATLAS_LZ4_VECTORS_H */")


if __name__ == "__main__":
    main()
